import os

DEBUG = True 

# Cache
CACHE_TYPE = "simple"
CACHE_DEFAULT_TIMEOUT = 300000

# Pagination
PAGE_SIZE = 10
VISIBLE_PAGE_COUNT = 10

# Twitter
# TODO(zooraze): pull configuration from environment variables
TWITTER_CONSUMER_KEY = 'YOUR_TWITTER_CONSUMER_KEY'
TWITTER_CONSUMER_SECRET = 'YOUR_TWITTER_CONSUMER_SECRET'
TWITTER_ACCESS_TOKEN = 'YOUR_TWITTER_ACCESS_TOKEN'
TWITTER_ACCESS_TOKEN_SECRET = 'YOUR_TWITTER_ACCESS_TOKEN_SECRET'